const RS = {
    PHRASE_SplashIntro: "A more civilized way to pay for things.",
    LABEL_Continue: "Continue",
    LABEL_Back: "Back",
    LABEL_TryToUseMyLocation: "Try to use my location",
    LABEL_AddAccount: "Add Account",
    PHRASE_AddAccountIntro: "Invent your new account number or recover it from memory.",
    ARIA_TapToGetStarted: "Tap to get started.",
    LABEL_BranchLatitudeLongitude: "Branch Latitude/Longitude",
    LABEL_Latitude: "Latitude",
    LABEL_Longitude: "Longitude",
    PHRASE_UnableToRetreiveYourLocation: "Unable to retreive your location.",
    LABEL_MyShortMemorableSentence: "My short memorable sentence",
    PHRASE_LatitudeInvalid: "Latitude should be between -80.0 and +80.0",
    PHRASE_LongitudeInvalid: "Longitude should be between -180.0 and +180.0",
    PHRASE_MoreWordsOrLettersRequired: "More words or letters are required.",
    PHRASE_UnableToAccessStorageOnThisDevice: "Unable to access storage on this device.",
    ARIA_OpenMenu: "Open menu",
    ARIA_ExitMenu: "Exit menu",
    LABEL_MyAccount: "My Account",
    LABEL_AcceptAPayment: "Accept a payment",
    ARIA_AcceptAPayment: "Accept a payment for your resource or time.",
    DECIMAL: ".",
    THOUSANDS_DELIMITER: ",",
    ARIA_AmountAsCivilizedTime: "Amount of civilized money (seconds in time.)",
    ARIA_AmountAsHours: "Amount converted to hours.",
    ARIA_AmountAsUSD: "Amount converted to US dollars.",
    LABEL_Amount: "Amount",
    LABEL_Memo: "Memo",
    LABEL_SharePaymentLink: "Share payment link",
    LABEL_UNSPSCFull: "United Nations Standard Products and Services Code (UNSPSC)",
    LABEL_UNSPSCShort: "UNSPSC",
    LABEL_Payer: "Payer",
    LABEL_ProofOfTime: "Proof of Time",
   
    LABEL_ScanAPayersApp: "Scan a payer's app",
    LABEL_CaptureProofOfTime: "Capture proof of time",
    LABEL_RecordASignature: "Record a signature",
    LABEL_TakeAPhoto: "Take a photo/selfie",
    PHRASE_ProofOfTimePhotosShouldBeRelevant: "Your Proof of Time photo (or selfie) should have the payer, work or endeavour in frame.",
    PHRASE_TapToPaySomeone: "Tap to pay someone",
    PHRASE_InvalidQREncountered: "Invalid CivilMoney info encountered",
    LABEL_DataReceived: "Data received",
    PHRASE_TheBranchOrAccountNumberIsNotBLANK: "The data already contains a branch or account number that is not {0}.",
    LABEL_Pay: "Pay",
    LABEL_To: "To",
    PHRASE_ThisPayeeIsNotInYourLedger: "This is a new payee/account number who you've not yet dealt with.",
    PHRASE_BLANKTimeOrBLANKHoursOrBLANKUSD: "{0} time, or {1} hours or {2} US dollars.",
    LABEL_SendAPayment: "Send a payment",
    LABEL_Summary: "Summary",
    LABEL_Ledger: "Ledger",
    ARIA_Ledger: "Review debits and credits.",
    LABEL_NicknameAccount: "Nickname Account",
    LABEL_RemoveAccount: "Remove Account",
    LABEL_Done: "Done",
    ARIA_CommitThisPaymentToYourLedger: "Commit this payment to your private ladger.",
    LABEL_ExportToAPaymentFile: "Export to a payment file for email/sharing",
    ARIA_SendThisPaymentAsAnEmailOrSomething: "Send this payment as an email attachment or other means.",
    // Part of a payment file name `CivilMoney Payment {uniqueid}.txt`
    LABEL_Payment: "Payment",
    // Displayed on the QR scanning dialog
    PHRASE_LookingForARecipientQRCode: "Looking for a CivilMoney Recipient QR Code",
    LABEL_TakeARelaventPhotoInstead: "Take a relavent photo/selfie instead",
    PHRASE_RelaventPhotoOfPayerOrResourceAccountNumberBLANK: "Relavent photo or selfie of payer or resource account number {0}",
    LABEL_TakeAVoiceRecording: "Take a voice recording",
    PHRASE_PayerBLANKPleaseSayImPayingToBLANKOnBLANKAtBLANKBLANKTimeHTML: "Payer {0}, please say something like:<quote>This is [your name], I'm paying {1} time to {2} on {3} at {4}.</quote>",
    LABEL_Branch: "Branch",
    LABEL_AccountNumber: "Account Number",
    PHRASE_AtLeastOneKindOfProofOfTimeIsRequired: "At lease one kind of proof of time is required.",
    PHRASE_PayMeQRCodeHint: "The above QR code can be scanned by a payer's CivilMoney App where they can sign from their own device. Have them show you their app's Proof of Time screen for scanning, or you can enter their branch and account number below, capturing their Proof of Time manually.",
    PHRASE_LookingForPayersQRSequence: "Looking for the payer's CivilMoney QR Sequence",
    // Error shown when a QR is scanned but the details are wrong.
    PHRASE_TransactionDetailsDontMatch: "Transaction details don't match.",
    // Error when a QR code payment is somehow missing any proof of time data.
    PHRASE_ProofOfTimeIsMissing: "Proof of time is missing.",
    PHRASE_PayerAccountDetailsMissing: "The payer's account number is missing.",
    PHRASE_AnInvalidPayerAccountNumberEntered: "An invalid payer account number has been entered.",
    PHRASE_AccountNumberExampleHTML: "An account number should be in the format of (Branch Latitude*10 Longitude*10) 0000 0000 0000 0000.<br/>Example:<br/>NY, NY USA is <b>40.7</b>30610,<b>-73.9</b>35242. Civil Branch would be 407 -739. A valid account number might be (407 -739) 1111 2222 3333 4444.",
    LABEL_CivilMoneyPaymentLink: "CivilMoney Payment Link",
    LABEL_NoUNSPSCSuggestions: "No UNSPSC code suggestions, try different search terms.",
    LABEL_InvalidUNSPSC: "Invalid UNSPSC code. Should be 8 digits.",
    LABEL_AmountMustBeGreaterThanZero: "Amount must be >= 1",
    LABEL_ImportSomebodysPayment: "Import somebody's payment",
    ARIA_ImportSomebodysPayment: "Import a CivilMoney payment .txt file that you've received from somebody.",
    // As in 'Amount earned.'
    LABEL_Earned: "Earned",
    // As in 'Amount spent.'
    LABEL_Spent: "Spent",
    // Hint reminding people looking at a ledger that positive things are all that really matter.
    PHRASE_TimeSpentOnPositiveThingsAreConsideredValuableHTML: "Time spent on any <u>positive</u> action, cause or endeavour is considered valuable and deserving of compensation in the civilized economy.",
    PHRASE_AreYouSureYouWantToRemoveAccountBLANKFromThisDevice: "Are you sure you want to remove {0} from this device?",
    LABEL_Import: "Import",
    PHRASE_InvalidTransactionData: "Invalid transaction data",
    PHRASE_UnrecognisedTransactionData: "Unrecognised payer and payee (this transaction won't appear in your ledger.)",
    LABEL_AlreadyImported: "Already imported",
    LABEL_Cancel: "Cancel",
    LABEL_Retry: "Retry",
    LABEL_Finalize: "Finalize",
    ARIA_Finalize: "Add this payment to your ledger.",
    PHRASE_TheRecipientAndPayerCantBeTheSameAccount: "The recipient and payer can't be the same account.",
    LABEL_BackupLedger: "Backup my ledger",
    ARIA_BackupLedger: "Transfer a copy of your ledger in *.csv format for safe keeping or use on another device.",
    LABEL_RestoreLedger: "Restore my ledger",
    ARIA_RestoreLedger: "Restore my ledger from a previously saved *.csv file",
    PHRASE_BLANKTransactionsCanBeImported: "{0} transaction(s) can be imported.",
    PHRASE_TheAccountNumberInTheFileIsInvalid: "The account number in the *.csv is invalid. It should be in the format of (Branch Latitude*10 Longitude*10) 0000 0000 0000 0000.",
    PHRASE_ImportTransactions: "Import transactions",
    PHRASE_BLANKTransactionsHaventBeenSubmittedToYourLocalBranchYet: "{0} transactions haven't yet been submitted to your local branch for your community's tax revenue generation. Feel free to submit them now if you're online and it's a convenient time. Civilised taxation is inverted, and does not come out of your earnings.",
    LABEL_SubmitToBranchLedger: "Submit to local branch",
    ARIA_SubmitToBranchLedger: "Submit transactions to your local branch. Civilised taxation is inverted, and does not come out of your earnings.",
    LABEL_ProofOfTimeIsMissing: "Proof of time is missing.",
    LABEL_BranchLedgerError: "Branch ledger error",
    LABEL_BLANKProblemsEncountered: "{0} problem(s) encountered",
    LABEL_ReviewProblems: "Review problems",
    LABEL_RemoveItem: "Remove item",
    PHRASE_ConfirmPaymentDelete: "Are you sure you want to delete this payment from your ledger?\r\n\r\nItems should only be removed in the event of a dispute or mistake. Arguments are settled amicably by default in the civilized economy. By that we mean, the seller may opt to keep their payment ledger entry, whilst you create your own refund by deleting yours.",
    LABEL_Help: "Help/About"
}